import "../globals.css";
import Providers from '@/components/Providers'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
  robots: {
    index: false,
    follow: false,
    nocache: true,
  },
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body><Providers>{children}</Providers></body>
    </html>
  )
}
